name: Lint and test

on:
  push:
    branches:
      - master
      - 20**
      - v20**
  workflow_dispatch:
  workflow_call:

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Find component directory
        id: find_component_dir
        run: echo "COMPONENT_DIR=$(find . -type d -name 'META-INF' -exec dirname {} \;)" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22.x'

      - name: Cache + Restore node_modules
        uses: actions/cache@v6
        with:
          path: |
              ${{ env.COMPONENT_DIR }}/.angular
              ${{ env.COMPONENT_DIR }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        working-directory: ${{ env.COMPONENT_DIR }}
        run: npm install

      - name: Lint
        working-directory: ${{ env.COMPONENT_DIR }}
        run: npx ng lint @servoy/servoyextracomponents --force --format json --output-file eslint-results.json
        continue-on-error: true

      - name: Annotate lint results
        if: always()
        uses: ataylorme/eslint-annotate-action@v4
        with:
          report-json: ${{ env.COMPONENT_DIR }}/eslint-results.json

      - name: Test
        working-directory: ${{ env.COMPONENT_DIR }}
        run: npm run test
